---
version: "3.8"
services:
  rundeck:
    image: "rundeck/rundeck:4.7.0"
    restart: "always"
    container_name: "rundeck"
    # https://docs.rundeck.com/docs/administration/configuration/docker.html#environment-variables
    environment:
      # general
      RUNDECK_GRAILS_URL: "http://localhost:4440"
      RUNDECK_SERVER_ADDRESS: "0.0.0.0"
      JVM_MAX_RAM_PERCENTAGE: "75"
      # database
      RUNDECK_DATABASE_DRIVER: "org.postgresql.Driver"
      RUNDECK_DATABASE_USERNAME: "rundeck"
      RUNDECK_DATABASE_PASSWORD: "rundeck"
      RUNDECK_DATABASE_URL: "jdbc:postgresql://postgres:5432/rundeck"
    env_file: ".env"
    depends_on:
      - "postgres"
    ports:
      - "4440:4440"
    volumes:
      - "/var/log/rundeck"
      - "/var/rundeck"
  postgres:
    image: "postgres:15.0"
    restart: "always"
    container_name: "rundeck_db"
    environment:
      POSTGRES_USER: "rundeck"
      POSTGRES_PASSWORD: "rundeck"
      POSTGRES_DB: "rundeck"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "rundeck"]
      timeout: 30s
      interval: 5s
      retries: 20
    volumes:
      - "/var/lib/postgresql/data"
