---
version: "3.1"
services:
  rundeck:
    image: "pemcconnell/rundeck:4.7.0"
    container_name: "rundeck"
    # https://docs.rundeck.com/docs/administration/configuration/docker.html#environment-variables
    environment:
      # general
      RUNDECK_GRAILS_URL: "http://localhost:4440"
      RUNDECK_SERVER_ADDRESS: "0.0.0.0"
      JVM_MAX_RAM_PERCENTAGE: "75"
      # database
      RUNDECK_DATABASE_DRIVER: "org.postgresql.Driver"
      RUNDECK_DATABASE_USERNAME: "rundeck"
      RUNDECK_DATABASE_PASSWORD: "rundeck"
      RUNDECK_DATABASE_URL: "jdbc:postgresql://postgres:5432/rundeck"
    env_file: ".env"
    depends_on:
      - "postgres"
      - "node1"
      - "node2"
    ports:
      - "4440:4440"
    volumes:
      - "~/.aws/:/home/rundeck/.aws/:ro"
      - "./kube.config:/home/rundeck/.kube/rundeck.yaml:ro"
      - "/var/log/rundeck"
      - "/var/rundeck"
      - "./resources.xml:/resources.xml"
    restart: "unless-stopped"

  #
  # all state to be stored in postgres (backups stored in ./backups/)
  #
  postgres:
    image: "postgres:15.0"
    container_name: "rundeck_db"
    environment:
      POSTGRES_USER: "rundeck"
      POSTGRES_PASSWORD: "rundeck"
      POSTGRES_DB: "rundeck"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "rundeck"]
      timeout: 30s
      interval: 5s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/postgresql/data"
      - "./backups:/docker-entrypoint-initdb.d/:rw"
    restart: "unless-stopped"

  #
  # some 'pretend' nodes so that we can show what a VM may look like in rundeck
  #
  node1:
    image: "lscr.io/linuxserver/openssh-server:latest"
    container_name: "node1"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Europe/London"
      SUDO_ACCESS: "true"
      PASSWORD_ACCESS: "true"
      USER_PASSWORD: "rundeck"
      USER_NAME: "rundeck"
    ports:
      - "7221:2222"
    restart: "unless-stopped"
  node2:
    image: "lscr.io/linuxserver/openssh-server:latest"
    container_name: "node2"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Europe/London"
      SUDO_ACCESS: "true"
      PASSWORD_ACCESS: "true"
      USER_PASSWORD: "rundeck"
      USER_NAME: "rundeck"
    ports:
      - "7222:2222"
    restart: "unless-stopped"
